
#Array de dicts que contiene nombre, contración y cantidad de los medicamentos disponibles

medicamentos = [
    {"nombre": "Acetaminofén", "concentracion": "500 mg", "cantidad": 150},
    {"nombre": "Acetaminofén", "concentracion": "150 mg/5 ml Jarabe", "cantidad": 45},
    {"nombre": "Ácido Acetilsalicílico", "concentracion": "100 mg", "cantidad": 200},
    {"nombre": "Albendazol", "concentracion": "400 mg", "cantidad": 30},
    {"nombre": "Alopurinol", "concentracion": "100 mg", "cantidad": 0},
    {"nombre": "Amoxicilina", "concentracion": "500 mg", "cantidad": 80},
    {"nombre": "Amlodipino", "concentracion": "5 mg", "cantidad": 120},
    {"nombre": "Atorvastatina", "concentracion": "20 mg", "cantidad": 95},
    {"nombre": "Atorvastatina", "concentracion": "40 mg", "cantidad": 0},
    {"nombre": "Azitromicina", "concentracion": "500 mg", "cantidad": 25},
    {"nombre": "Beclometasona", "concentracion": "250 mcg Inhalador", "cantidad": 15},
    {"nombre": "Captopril", "concentracion": "25 mg", "cantidad": 60},
    {"nombre": "Carbamacepina", "concentracion": "200 mg", "cantidad": 40},
    {"nombre": "Cefalexina", "concentracion": "500 mg", "cantidad": 55},
    {"nombre": "Ciprofloxacino", "concentracion": "500 mg", "cantidad": 30},
    {"nombre": "Clonazepam", "concentracion": "2 mg", "cantidad": 10},
    {"nombre": "Clotrimazol", "concentracion": "1% Crema", "cantidad": 20},
    {"nombre": "Diclofenaco", "concentracion": "50 mg", "cantidad": 110},
    {"nombre": "Diosmina", "concentracion": "500 mg", "cantidad": 0},
    {"nombre": "Doxiciclina", "concentracion": "100 mg", "cantidad": 35},
    {"nombre": "Enalapril", "concentracion": "20 mg", "cantidad": 140},
    {"nombre": "Espironolactona", "concentracion": "25 mg", "cantidad": 50},
    {"nombre": "Fluconazol", "concentracion": "150 mg", "cantidad": 18},
    {"nombre": "Fluoxetina", "concentracion": "20 mg", "cantidad": 45},
    {"nombre": "Furosemida", "concentracion": "40 mg", "cantidad": 75},
    {"nombre": "Glibenclamida", "concentracion": "5 mg", "cantidad": 90},
    {"nombre": "Hidroclorotiazida", "concentracion": "25 mg", "cantidad": 130},
    {"nombre": "Ibuprofeno", "concentracion": "400 mg", "cantidad": 200},
    {"nombre": "Ibuprofeno", "concentracion": "600 mg", "cantidad": 0},
    {"nombre": "Insulina Glargina", "concentracion": "100 UI/ml", "cantidad": 12},
    {"nombre": "Loratadina", "concentracion": "10 mg", "cantidad": 300},
    {"nombre": "Losartán Potásico", "concentracion": "50 mg", "cantidad": 500},
    {"nombre": "Losartán Potásico", "concentracion": "100 mg", "cantidad": 0},
    {"nombre": "Metformina", "concentracion": "850 mg", "cantidad": 400},
    {"nombre": "Metimazol", "concentracion": "5 mg", "cantidad": 20},
    {"nombre": "Metoclopramida", "concentracion": "10 mg", "cantidad": 65},
    {"nombre": "Metoprolol Succinato", "concentracion": "50 mg", "cantidad": 85},
    {"nombre": "Naproxeno", "concentracion": "500 mg", "cantidad": 120},
    {"nombre": "Nifedipino", "concentracion": "30 mg", "cantidad": 40},
    {"nombre": "Nitrofurantoína", "concentracion": "100 mg", "cantidad": 25},
    {"nombre": "Omeprazol", "concentracion": "20 mg", "cantidad": 600},
    {"nombre": "Prednisolona", "concentracion": "5 mg", "cantidad": 55},
    {"nombre": "Propranolol", "concentracion": "40 mg", "cantidad": 70},
    {"nombre": "Ranitidina", "concentracion": "150 mg", "cantidad": 0},
    {"nombre": "Salbutamol", "concentracion": "100 mcg Inhalador", "cantidad": 30},
    {"nombre": "Sertralina", "concentracion": "50 mg", "cantidad": 20},
    {"nombre": "Sulfato Ferroso", "concentracion": "200 mg", "cantidad": 180},
    {"nombre": "Tamsulosina", "concentracion": "0.4 mg", "cantidad": 50},
    {"nombre": "Tramadol", "concentracion": "50 mg", "cantidad": 0},
    {"nombre": "Vitamina C", "concentracion": "500 mg", "cantidad": 250},
]